[package]
name = "builder_test"
version = "0.1.0"
authors = ["Doom <clement.doumergue@epitech.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
builder_derive = { path = "./builder_derive" }
